<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IdentityHub.Domain\IdentityHub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Login\" />
    <Folder Include="Features\RefreshTokens\" />
    <Folder Include="Features\Register\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
